// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/23/2024, 12:36:55 PM
const configMerger = require("/home/klab/Websites/DMS/nuxt-formkit/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/klab/Websites/DMS/nuxt-formkit/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/klab/Websites/DMS/nuxt-formkit/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/klab/Websites/DMS/nuxt-formkit/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/klab/Websites/DMS/nuxt-formkit/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/klab/Websites/DMS/nuxt-formkit/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/klab/Websites/DMS/nuxt-formkit/app/plugins/**/*.{js,ts,mjs}","/home/klab/Websites/DMS/nuxt-formkit/app/composables/**/*.{js,ts,mjs}","/home/klab/Websites/DMS/nuxt-formkit/app/utils/**/*.{js,ts,mjs}","/home/klab/Websites/DMS/nuxt-formkit/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/klab/Websites/DMS/nuxt-formkit/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/klab/Websites/DMS/nuxt-formkit/app/app.config.{js,ts,mjs}"] } }));

module.exports = (() => {const cfg=config;cfg["content"]["files"]["11"] = "/home/klab/Websites/DMS/nuxt-formkit/formkit.theme.ts";cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})()
